PiuDecorations/urls.py
# -*- coding: utf-8 -*-
"""PiuDecorations URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(
        r'^client/',
        include('client.urls', namespace='client')
    ),
    url(
        r'^order-raise/',
        include('order_raise.urls', namespace='order_raise')
    ),
    url(
        r'^',
        include('dashboard.urls', namespace='dashboard')
    ),
]

client/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

from .views import (
    ClientCreateView, ClientListView,
    ClientUpdateView, ClientDeleteView
)


urlpatterns = [
    url(r'create/$', ClientCreateView.as_view(), name='create'),
    url(r'update/(?P<pk>[0-9]*)/$', ClientUpdateView.as_view(), name='edit'),
    url(r'delete/(?P<pk>[0-9]*)/$', ClientDeleteView.as_view(), name='delete'),
    url(r'$', ClientListView.as_view(), name='list'),
]

client/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from safedelete.models import SafeDeleteModel, SOFT_DELETE_CASCADE


class Client(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE

    identifier = models.IntegerField(
        verbose_name=u'Identificación',
        null=True,
        blank=True
    )
    name = models.CharField(
        verbose_name=u'Nombre',
        max_length=255
    )
    direction = models.CharField(
        verbose_name=u'Dirección',
        max_length=255
    )
    email = models.EmailField(
        verbose_name=u'Correo',
    )
    phone = models.IntegerField(
        verbose_name=u'Teléfono',
    )

    created_at = models.DateTimeField(
        verbose_name=u'Fecha de creación',
        auto_now_add=True
    )

    created_by = models.ForeignKey(
        User,
        verbose_name='Creado por',
        related_name='clients',
        related_query_name='client'
    )

    def __unicode__(self):
        return "%d - %s" % (self.id, self.name)

    def __str__(self):
        return "%d - %s" % (self.id, self.name)

    def getIdentifier(self):
        return self.identifier

    def getName(self):
        return self.name

    def getEmail(self):
        return self.email

    def createdBy(self):
        return self.created_by

client/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['created_at', 'created_by']
        widgets = {
            'identifier': forms.NumberInput(attrs={'type': 'tel'}),
            'phone': forms.NumberInput(attrs={'type': 'tel'})
        }

client/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from mixin.createdbymixin import CreatedByMixin

from .models import Client
from .forms import ClientForm


class ClientCreateView(CreatedByMixin, CreateView):
    context_object_name = 'client'
    form_class = ClientForm
    model = Client
    queryset = Client.objects.all()
    template_name = 'client-create.html'
    success_url = reverse_lazy('client:list')


class ClientListView(ListView):
    context_object_name = 'clients'
    model = Client
    queryset = Client.objects.all()
    template_name = 'client-list.html'


class ClientUpdateView(UpdateView):
    context_object_name = 'client'
    form_class = ClientForm
    model = Client
    queryset = Client.objects.all()
    template_name = 'client-edit.html'
    success_url = reverse_lazy('client:list')


class ClientDeleteView(DeleteView):
    model = Client
    queryset = Client.objects.all()
    success_url = reverse_lazy('client:list')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return self.delete(request, *args, **kwargs)

client/templates/client-create.html
{% extends "layout/dashboard-template.html" %}
{% load bootstrap3 %}

{% block page-title %}
  Crear Cliente
{% endblock page-title %}
{% block main-content %}
  {# Display a form #}
  <form method="post" class="form" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "star" %} Crear
      </button>
    {% endbuttons %}
  </form>
{% endblock main-content %}

client/templates/client-edit.html
{% extends "layout/dashboard-template.html" %}
{% load bootstrap3 %}

{% block page-title %}
  Editar Cliente
{% endblock page-title %}
{% block main-content %}
  {# Display a form #}
  <form method="post" class="form" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        <b class="fa fa-plus"></b> Crear
      </button>
    {% endbuttons %}
  </form>
{% endblock main-content %}

client/templates/client-list.html
{% extends "layout/dashboard-template.html" %}
{% load bootstrap3 %}

{% block page-title %}
  Lista de Clientes
{% endblock page-title %}
{% block main-content %}
  {% for client in clients %}
    {{client}}
    
    <a href="{% url 'client:edit' pk=client.id %}">Editar cliente</a>
    <a href="{% url 'client:delete' pk=client.id %}">Eliminar cliente</a>
  {% endfor %}
{% endblock main-content %}